#include<iostream>
#include<string>
using namespace std;
int main() {
    string search;
    cout<<"What do you want to search?:";
    cin >> search;
    if (search == "COMPUTER"){
        cout <<"An electronic device that can run multiple task";
    }
    else if(search == "ABACUS"){
        cout <<"First computer";
    }
    else if (search == "NAPIER's BONES"){
        cout << "Manually operated computer ";
    }
    else if (search == "PASCALINE"){
        cout << "Arithmetic Machine";
    }
    else if (search == "STEPPED RECKONER"){
        cout << "Created by Gottfried Wilhelm Leibniz";
    }
    else if (search == "ANALYTICAL ENGINE"){
        cout << " Created by Charles Babbage";
    }
    else if (search == "TABULATING MACHINE"){
        cout << "Created by Herman Hollerith";
    }
    else if (search == "DIFFERENTIAL ANALYZER"){
        cout << "1st electronic computer...";
    }
    else if (search == "MARK I"){
        cout << "First prorammable computer";
    }
    else if (search == "FIRST GEN COMPUTER"){
        cout << "Uses vaccum tubes";
    }
    else if (search == "SECOND GEN COMOUTER"){
        cout << "Uses transistors";
    }
    else if (search == "THIRD GEN COMOUTER"){
        cout << "Used integrated circuits";
    }
    else if (search == "FOURTH GEN COMPUTER"){
        cout << " Uses VLSI (Very Large Scale Integrated) ";
    }
    else if (search == "FIFTH GEN"){
        cout << "ULSI was used";
    }
    else if (search == "DIGITAL COMPUTER"){
        cout << "Capable of processing information in discrete form";
    }
    else if (search == "ANALOG COMP"){
        cout << "Data generated by ongoing physical process...";
    }
    else if (search == "HYBRID COMP"){
        cout << "Combination of Digital and Analog";
    }
    else if (search == "SUPERCOMPUTER"){
        cout << "Most powerful comouter and expensive";
    }
    else if (search == "MAINFRAME COMP"){
        cout << "Large and powerful";
    }
    else if (search == "MINI COMP"){
        cout << "Smaller and less powerful";
    }
    else if (search == "PERSONAL COMP"){
        cout << "Designed for everyday use like phones";
    }
    else if (search == "WORKSTATIONS"){
        cout << "High performance";
    }
    else if (search == "EMBEDDED SYSTEM"){
        cout << "Specialized computers";
    }
    else if (search == "MOBILE DEVICES"){
        cout << "Portable computers";
    }
    else if (search == "PERIPHERAL DEVICES"){
        cout << "Device like mouse, keyboard etc";
    }
    else if (search == "RANDOM ACCESS MEMORY"){
        cout << "Also known as RAM";
    }
    else if (search == "HARD DISK DRIVE"){
        cout << "Also known as HDD";
    }
    else if (search == "SYSTEM SOFTWARE"){
        cout << "Without this, our computer won't run";
    }
    else if (search == "APPLICATION SOFTWARE"){
        cout << "Without this, our computer could still run";
    }
    else if (search == "CRACKER"){
        cout << "Will try to steal your info";
    }
    else {cout<<"Invalid Input";
    }
    return 0;
}